[tool.pytest.ini_options]
#addopts="-l -v --durations=10"
markers=[
    "mobile: тесты мобильной версии пользрвательского интерфейса",
    "desktop: тесты компьютероной версии пользрвательского интерфейса"
]
